//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.DeviceSuite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.DeviceSuite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Gurux Device Suite Community Edition.
        /// </summary>
        internal static string AboutGuruxDeviceSuiteTxt {
            get {
                return ResourceManager.GetString("AboutGuruxDeviceSuiteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionTxt {
            get {
                return ResourceManager.GetString("ActionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must install needed Device AddIns first..
        /// </summary>
        internal static string AddInsNotInstalled {
            get {
                return ResourceManager.GetString("AddInsNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedTxt {
            get {
                return ResourceManager.GetString("AdvancedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string AllFilesTxt {
            get {
                return ResourceManager.GetString("AllFilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux Device Suite AMI.
        /// </summary>
        internal static string AmiTxt {
            get {
                return ResourceManager.GetString("AmiTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string BackArrowTxt {
            get {
                return ResourceManager.GetString("BackArrowTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackTxt {
            get {
                return ResourceManager.GetString("BackTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box without saving any changes you have made..
        /// </summary>
        internal static string CancelHelp {
            get {
                return ResourceManager.GetString("CancelHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTxt {
            get {
                return ResourceManager.GetString("CancelTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoriesTxt {
            get {
                return ResourceManager.GetString("CategoriesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Properties.
        /// </summary>
        internal static string CategoryPropertiesTxt {
            get {
                return ResourceManager.GetString("CategoryPropertiesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Settings.
        /// </summary>
        internal static string CategorySettingsTxt {
            get {
                return ResourceManager.GetString("CategorySettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Wizard.
        /// </summary>
        internal static string CategoryWizardTxt {
            get {
                return ResourceManager.GetString("CategoryWizardTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose source.
        /// </summary>
        internal static string ChooseFileTypeTxt {
            get {
                return ResourceManager.GetString("ChooseFileTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose properties.
        /// </summary>
        internal static string ChoosePropertiesTxt {
            get {
                return ResourceManager.GetString("ChoosePropertiesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are still active schedules. Are you sure you want to close Gurux Device Suite..
        /// </summary>
        internal static string CloseAndKillSchedulesTxt {
            get {
                return ResourceManager.GetString("CloseAndKillSchedulesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the connection is made automatically at startup..
        /// </summary>
        internal static string ConnectAtStartupHelp {
            get {
                return ResourceManager.GetString("ConnectAtStartupHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string ConnectingTxt {
            get {
                return ResourceManager.GetString("ConnectingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Delay Time must be a positive integer..
        /// </summary>
        internal static string ConnectionDelayTimeIncorrectTxt {
            get {
                return ResourceManager.GetString("ConnectionDelayTimeIncorrectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Delay Time.
        /// </summary>
        internal static string ConnectionDelayTimeTxt {
            get {
                return ResourceManager.GetString("ConnectionDelayTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Fail Try Count must be a positive integer..
        /// </summary>
        internal static string ConnectionFailTryCountIncorrectTxt {
            get {
                return ResourceManager.GetString("ConnectionFailTryCountIncorrectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Fail Try Count.
        /// </summary>
        internal static string ConnectionFailTryCountTxt {
            get {
                return ResourceManager.GetString("ConnectionFailTryCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Fail Wait Time.
        /// </summary>
        internal static string ConnectionFailWaitTime {
            get {
                return ResourceManager.GetString("ConnectionFailWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Fail Wait Time must be a positive integer..
        /// </summary>
        internal static string ConnectionFailWaitTimeIncorrectTxt {
            get {
                return ResourceManager.GetString("ConnectionFailWaitTimeIncorrectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright© 1998-2014 Gurux Ltd.
        ///All rights reserved..
        /// </summary>
        internal static string CopyrightTxt {
            get {
                return ResourceManager.GetString("CopyrightTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyTxt {
            get {
                return ResourceManager.GetString("CopyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomProtocolTxt {
            get {
                return ResourceManager.GetString("CustomProtocolTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string DailyTxt {
            get {
                return ResourceManager.GetString("DailyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Month.
        /// </summary>
        internal static string DayOfMonthTxt {
            get {
                return ResourceManager.GetString("DayOfMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Week.
        /// </summary>
        internal static string DayOfWeekTxt {
            get {
                return ResourceManager.GetString("DayOfWeekTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTxt {
            get {
                return ResourceManager.GetString("DeleteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionTxt {
            get {
                return ResourceManager.GetString("DescriptionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        internal static string DeselectAllTxt {
            get {
                return ResourceManager.GetString("DeselectAllTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Device {
            get {
                object obj = ResourceManager.GetObject("Device", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceCategories {
            get {
                object obj = ResourceManager.GetObject("DeviceCategories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceCategory {
            get {
                object obj = ResourceManager.GetObject("DeviceCategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceConnected {
            get {
                object obj = ResourceManager.GetObject("DeviceConnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceDirty {
            get {
                object obj = ResourceManager.GetObject("DeviceDirty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceDisconnect {
            get {
                object obj = ResourceManager.GetObject("DeviceDisconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux Device Suite Editor.
        /// </summary>
        internal static string DeviceEditorTxt {
            get {
                return ResourceManager.GetString("DeviceEditorTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceError {
            get {
                object obj = ResourceManager.GetObject("DeviceError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceGroup {
            get {
                object obj = ResourceManager.GetObject("DeviceGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceGroupError {
            get {
                object obj = ResourceManager.GetObject("DeviceGroupError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the device group. Name cannot be an empty field..
        /// </summary>
        internal static string DeviceGroupNameHelp {
            get {
                return ResourceManager.GetString("DeviceGroupNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Group Settings.
        /// </summary>
        internal static string DeviceGroupSettingsTxt {
            get {
                return ResourceManager.GetString("DeviceGroupSettingsTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceHeader {
            get {
                object obj = ResourceManager.GetObject("DeviceHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Import.
        /// </summary>
        internal static string DeviceImportTxt {
            get {
                return ResourceManager.GetString("DeviceImportTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceList {
            get {
                object obj = ResourceManager.GetObject("DeviceList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceListError {
            get {
                object obj = ResourceManager.GetObject("DeviceListError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list files (*.gxd)|*.gxd|All files (*.*)|*.*.
        /// </summary>
        internal static string DeviceListFilterTxt {
            get {
                return ResourceManager.GetString("DeviceListFilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device List Settings.
        /// </summary>
        internal static string DeviceListSettingsTxt {
            get {
                return ResourceManager.GetString("DeviceListSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list.
        /// </summary>
        internal static string DeviceListTxt {
            get {
                return ResourceManager.GetString("DeviceListTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceMonitor {
            get {
                object obj = ResourceManager.GetObject("DeviceMonitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the device. Name cannot be an empty field..
        /// </summary>
        internal static string DeviceNameHelp {
            get {
                return ResourceManager.GetString("DeviceNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        internal static string DeviceNameTxt {
            get {
                return ResourceManager.GetString("DeviceNameTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceNotifies {
            get {
                object obj = ResourceManager.GetObject("DeviceNotifies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Profile already exists. Are you sure that you want to replace it?.
        /// </summary>
        internal static string DeviceProfileExistsTxt {
            get {
                return ResourceManager.GetString("DeviceProfileExistsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Device Profile that defines the behavior of the device. This is created using GXDeviceEditor..
        /// </summary>
        internal static string DeviceProfileHelp {
            get {
                return ResourceManager.GetString("DeviceProfileHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Profiles.
        /// </summary>
        internal static string DeviceProfilesTxt {
            get {
                return ResourceManager.GetString("DeviceProfilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to use Gurux Device Profile Wizard..
        /// </summary>
        internal static string DeviceProfileWizardCaption {
            get {
                return ResourceManager.GetString("DeviceProfileWizardCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Gurux Device Profile Wizard you can create Device Profiles. To Device Profile you describe what kind of data you want to read from the device..
        /// </summary>
        internal static string DeviceProfileWizardInfo {
            get {
                return ResourceManager.GetString("DeviceProfileWizardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Profile Wizard.
        /// </summary>
        internal static string DeviceProfileWizardTitle {
            get {
                return ResourceManager.GetString("DeviceProfileWizardTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceProperties {
            get {
                object obj = ResourceManager.GetObject("DeviceProperties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceProperty {
            get {
                object obj = ResourceManager.GetObject("DeviceProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevicePropertyChanged {
            get {
                object obj = ResourceManager.GetObject("DevicePropertyChanged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevicePropertyChanged2 {
            get {
                object obj = ResourceManager.GetObject("DevicePropertyChanged2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DevicePropertyError {
            get {
                object obj = ResourceManager.GetObject("DevicePropertyError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceRead {
            get {
                object obj = ResourceManager.GetObject("DeviceRead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Settings.
        /// </summary>
        internal static string DeviceSettingsTxt {
            get {
                return ResourceManager.GetString("DeviceSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Device Template and used protocol..
        /// </summary>
        internal static string DeviceSettingsWizardDescription {
            get {
                return ResourceManager.GetString("DeviceSettingsWizardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DeviceStatusTxt {
            get {
                return ResourceManager.GetString("DeviceStatusTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceStop {
            get {
                object obj = ResourceManager.GetObject("DeviceStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceTable {
            get {
                object obj = ResourceManager.GetObject("DeviceTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeviceTables {
            get {
                object obj = ResourceManager.GetObject("DeviceTables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string DeviceTypeTxt {
            get {
                return ResourceManager.GetString("DeviceTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Wizard.
        /// </summary>
        internal static string DeviceWizardTxt {
            get {
                return ResourceManager.GetString("DeviceWizardTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DeviceWrite {
            get {
                object obj = ResourceManager.GetObject("DeviceWrite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux Device Suite Director.
        /// </summary>
        internal static string DirectorTxt {
            get {
                return ResourceManager.GetString("DirectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Actions.
        /// </summary>
        internal static string DisabledActionsTxt {
            get {
                return ResourceManager.GetString("DisabledActionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Groups.
        /// </summary>
        internal static string DisabledGroupsTxt {
            get {
                return ResourceManager.GetString("DisabledGroupsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable monitoring..
        /// </summary>
        internal static string DisableMonitorText {
            get {
                return ResourceManager.GetString("DisableMonitorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable reading..
        /// </summary>
        internal static string DisableReadText {
            get {
                return ResourceManager.GetString("DisableReadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable scheduling..
        /// </summary>
        internal static string DisableScheduleText {
            get {
                return ResourceManager.GetString("DisableScheduleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable writing..
        /// </summary>
        internal static string DisableWriteText {
            get {
                return ResourceManager.GetString("DisableWriteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        internal static string DisconnectingTxt {
            get {
                return ResourceManager.GetString("DisconnectingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneTxt {
            get {
                return ResourceManager.GetString("DoneTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove .
        /// </summary>
        internal static string DoYouWantToRemoveTxt {
            get {
                return ResourceManager.GetString("DoYouWantToRemoveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit value.
        /// </summary>
        internal static string EditValueTxt {
            get {
                return ResourceManager.GetString("EditValueTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list name can&apos;t be empty..
        /// </summary>
        internal static string ErrDevListNameEmptyTxt {
            get {
                return ResourceManager.GetString("ErrDevListNameEmptyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not be empty..
        /// </summary>
        internal static string ErrNameEmptyTxt {
            get {
                return ResourceManager.GetString("ErrNameEmptyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Try Count must be a positive integer..
        /// </summary>
        internal static string ErrorTryCountIncorrectTxt {
            get {
                return ResourceManager.GetString("ErrorTryCountIncorrectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Try Count.
        /// </summary>
        internal static string ErrorTryCountTxt {
            get {
                return ResourceManager.GetString("ErrorTryCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Wait Time must be a positive decimal number..
        /// </summary>
        internal static string ErrorWaitTimeIncorrectTxt {
            get {
                return ResourceManager.GetString("ErrorWaitTimeIncorrectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Wait Time.
        /// </summary>
        internal static string ErrorWaitTimeTxt {
            get {
                return ResourceManager.GetString("ErrorWaitTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node not selected..
        /// </summary>
        internal static string ErrUnknownNodeTxt {
            get {
                return ResourceManager.GetString("ErrUnknownNodeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported Gurux Device Profile files (*.gxz)|*.gxz|.
        /// </summary>
        internal static string ExportedFilesFileTxt {
            get {
                return ResourceManager.GetString("ExportedFilesFileTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap factory {
            get {
                object obj = ResourceManager.GetObject("factory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishTxt {
            get {
                return ResourceManager.GetString("FinishTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For information about Gurux products see:.
        /// </summary>
        internal static string ForMoreInfoTxt {
            get {
                return ResourceManager.GetString("ForMoreInfoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Device.
        /// </summary>
        internal static string FromDeviceTxt {
            get {
                return ResourceManager.GetString("FromDeviceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTxt {
            get {
                return ResourceManager.GetString("GeneralTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuruxAMI connection settings must be set before GuruxAMI can be use..
        /// </summary>
        internal static string GuruxAMINotInitialized {
            get {
                return ResourceManager.GetString("GuruxAMINotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurux Device Suite.
        /// </summary>
        internal static string GuruxDeviceSuiteTxt {
            get {
                return ResourceManager.GetString("GuruxDeviceSuiteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Help topic is associated with this item..
        /// </summary>
        internal static string HelpNotAvailable {
            get {
                return ResourceManager.GetString("HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string HourTxt {
            get {
                return ResourceManager.GetString("HourTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing properties from selected Device.
        /// </summary>
        internal static string ImportingFromDeviceTxt {
            get {
                return ResourceManager.GetString("ImportingFromDeviceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Resend Count value..
        /// </summary>
        internal static string IncorrectResendCountTxt {
            get {
                return ResourceManager.GetString("IncorrectResendCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Profile settings are not present. Do you want to install them online from Gurux Web?.
        /// </summary>
        internal static string InstallManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("InstallManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string IntervalTxt {
            get {
                return ResourceManager.GetString("IntervalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid day of month. Day of month must be between 1 and 31..
        /// </summary>
        internal static string InvalidDayOfMonthTxt {
            get {
                return ResourceManager.GetString("InvalidDayOfMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid day of month. Day of month must be between 1 and 31..
        /// </summary>
        internal static string InvalidDayOfMonthTxt1 {
            get {
                return ResourceManager.GetString("InvalidDayOfMonthTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interval. Interval must be over zero..
        /// </summary>
        internal static string InvalidIntervalTxt {
            get {
                return ResourceManager.GetString("InvalidIntervalTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction count. Transaction count must be over zero..
        /// </summary>
        internal static string InvalidTransactionCountTxt {
            get {
                return ResourceManager.GetString("InvalidTransactionCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is successfully exported..
        /// </summary>
        internal static string IsExportedTxt {
            get {
                return ResourceManager.GetString("IsExportedTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap leaf {
            get {
                object obj = ResourceManager.GetObject("leaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leafanim {
            get {
                object obj = ResourceManager.GetObject("leafanim", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap leaferror {
            get {
                object obj = ResourceManager.GetObject("leaferror", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap like {
            get {
                object obj = ResourceManager.GetObject("like", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        internal static string ManufacturersTxt {
            get {
                return ResourceManager.GetString("ManufacturersTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Simultaneous Transactions must be integer with value of 1 or higher..
        /// </summary>
        internal static string MaxThreadCountIncorrectTxt {
            get {
                return ResourceManager.GetString("MaxThreadCountIncorrectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Simultaneous Transactions.
        /// </summary>
        internal static string MaxThreadCountTxt {
            get {
                return ResourceManager.GetString("MaxThreadCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media used for connecting to the physical device..
        /// </summary>
        internal static string MediaListHelp {
            get {
                return ResourceManager.GetString("MediaListHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap middle {
            get {
                object obj = ResourceManager.GetObject("middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutely.
        /// </summary>
        internal static string MinuteTxt {
            get {
                return ResourceManager.GetString("MinuteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string MonitorTxt {
            get {
                return ResourceManager.GetString("MonitorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string MonthlyTxt {
            get {
                return ResourceManager.GetString("MonthlyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameTxt {
            get {
                return ResourceManager.GetString("NameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string NextArrowTxt {
            get {
                return ResourceManager.GetString("NextArrowTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextTxt {
            get {
                return ResourceManager.GetString("NextTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuruxAMI database is created but there is no Data Collector. Do you want to add one?.
        /// </summary>
        internal static string NoDataCollectorTxt {
            get {
                return ResourceManager.GetString("NoDataCollectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device models..
        /// </summary>
        internal static string NoDeviceModelsTxt {
            get {
                return ResourceManager.GetString("NoDeviceModelsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices published..
        /// </summary>
        internal static string NoDevicesPublishedTxt {
            get {
                return ResourceManager.GetString("NoDevicesPublishedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifies.
        /// </summary>
        internal static string NotifiesTxt {
            get {
                return ResourceManager.GetString("NotifiesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify categories.
        /// </summary>
        internal static string NotifyCategoriesTxt {
            get {
                return ResourceManager.GetString("NotifyCategoriesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the dialog box and saves any changes you have made..
        /// </summary>
        internal static string OKHelp {
            get {
                return ResourceManager.GetString("OKHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKTxt {
            get {
                return ResourceManager.GetString("OKTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        internal static string OnceTxt {
            get {
                return ResourceManager.GetString("OnceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string OpenProjectTxt {
            get {
                return ResourceManager.GetString("OpenProjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to override previously registered device type?.
        /// </summary>
        internal static string OverregisterTxt {
            get {
                return ResourceManager.GetString("OverregisterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Wizard.
        /// </summary>
        internal static string PropertyWizardTxt {
            get {
                return ResourceManager.GetString("PropertyWizardTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Settings.
        /// </summary>
        internal static string ProtocolSettingsTxt {
            get {
                return ResourceManager.GetString("ProtocolSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications updated..
        /// </summary>
        internal static string ProtocolsUpdatedTxt {
            get {
                return ResourceManager.GetString("ProtocolsUpdatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Device Profile will published after check..
        /// </summary>
        internal static string PublishedDescription {
            get {
                return ResourceManager.GetString("PublishedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device Profile is checked before publishing. If there are any problems we will let you know. Thank you for your contribution..
        /// </summary>
        internal static string PublishedInfo {
            get {
                return ResourceManager.GetString("PublishedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for publishing your Device Pofile..
        /// </summary>
        internal static string PublishedTitle {
            get {
                return ResourceManager.GetString("PublishedTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Publisher {
            get {
                object obj = ResourceManager.GetObject("Publisher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Gurux device publisher you can publish your Device Profiles so all Gurux Community members can use them.
        ///
        ///You will find more information from Gurux Device publisher from 
        ///www.gurux.org/DevicePublisher.
        /// </summary>
        internal static string PublisherInfoDescription {
            get {
                return ResourceManager.GetString("PublisherInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to use Gurux Device Profile Publisher..
        /// </summary>
        internal static string PublisherInfoTitle {
            get {
                return ResourceManager.GetString("PublisherInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Profile publishing failed because there is not enought data..
        /// </summary>
        internal static string PublishFailedNotEnoughtData {
            get {
                return ResourceManager.GetString("PublishFailedNotEnoughtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading....
        /// </summary>
        internal static string ReadingTxt {
            get {
                return ResourceManager.GetString("ReadingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string ReadTxt {
            get {
                return ResourceManager.GetString("ReadTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyTxt {
            get {
                return ResourceManager.GetString("ReadyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval between read operations when monitoring is active.
        /// </summary>
        internal static string RefreshRateHelp {
            get {
                return ResourceManager.GetString("RefreshRateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshTxt {
            get {
                return ResourceManager.GetString("RefreshTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove all categories?.
        /// </summary>
        internal static string RemoveAllCategoriesTxt {
            get {
                return ResourceManager.GetString("RemoveAllCategoriesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove all tables?.
        /// </summary>
        internal static string RemoveAllTablesTxt {
            get {
                return ResourceManager.GetString("RemoveAllTablesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected Data Collector(s)?.
        /// </summary>
        internal static string RemoveDataCollectorTxt {
            get {
                return ResourceManager.GetString("RemoveDataCollectorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected device group?.
        /// </summary>
        internal static string RemoveDeviceGroupTxt {
            get {
                return ResourceManager.GetString("RemoveDeviceGroupTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected device profile(s)?.
        /// </summary>
        internal static string RemoveDeviceProfilesTxt {
            get {
                return ResourceManager.GetString("RemoveDeviceProfilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected device(s)?.
        /// </summary>
        internal static string RemoveDeviceTxt {
            get {
                return ResourceManager.GetString("RemoveDeviceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete selected item?.
        /// </summary>
        internal static string RemoveItemTxt {
            get {
                return ResourceManager.GetString("RemoveItemTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveTxt {
            get {
                return ResourceManager.GetString("RemoveTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Mode.
        /// </summary>
        internal static string RepeatModeTxt {
            get {
                return ResourceManager.GetString("RepeatModeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Count:.
        /// </summary>
        internal static string ResendCountTxt {
            get {
                return ResourceManager.GetString("ResendCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetTxt {
            get {
                return ResourceManager.GetString("ResetTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart application to update AddIns..
        /// </summary>
        internal static string RestartToUpdateAddins {
            get {
                return ResourceManager.GetString("RestartToUpdateAddins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must be restarted to apply the changes..
        /// </summary>
        internal static string RestartTxt {
            get {
                return ResourceManager.GetString("RestartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Default Settings.
        /// </summary>
        internal static string SaveAsDefaultSettingsTxt {
            get {
                return ResourceManager.GetString("SaveAsDefaultSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes you made?.
        /// </summary>
        internal static string SaveChangesQuestionTxt {
            get {
                return ResourceManager.GetString("SaveChangesQuestionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes you made to the device list?.
        /// </summary>
        internal static string SaveChangesTxt {
            get {
                return ResourceManager.GetString("SaveChangesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists available actions..
        /// </summary>
        internal static string ScheduleActionHelp {
            get {
                return ResourceManager.GetString("ScheduleActionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay time of the connection in milliseconds..
        /// </summary>
        internal static string ScheduleConnectionDelayTimeHelp {
            get {
                return ResourceManager.GetString("ScheduleConnectionDelayTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day of month when the schedule is performed. If the number of the day is 29, 30 or 31, the schedule is done in those months that have that day..
        /// </summary>
        internal static string ScheduleDayOfMonthHelp {
            get {
                return ResourceManager.GetString("ScheduleDayOfMonthHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Editor.
        /// </summary>
        internal static string ScheduleEditorTxt {
            get {
                return ResourceManager.GetString("ScheduleEditorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule end time is before start time..
        /// </summary>
        internal static string ScheduleEndBeforeStartTxt {
            get {
                return ResourceManager.GetString("ScheduleEndBeforeStartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date when the schedule ends, optional..
        /// </summary>
        internal static string ScheduleEndDateHelp {
            get {
                return ResourceManager.GetString("ScheduleEndDateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule End Date.
        /// </summary>
        internal static string ScheduleEndTimeTxt {
            get {
                return ResourceManager.GetString("ScheduleEndTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule finished..
        /// </summary>
        internal static string ScheduleEndTxt {
            get {
                return ResourceManager.GetString("ScheduleEndTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of retries if an error happens..
        /// </summary>
        internal static string ScheduleErrorTryCountHelp {
            get {
                return ResourceManager.GetString("ScheduleErrorTryCountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The waiting time before retry if an error happens..
        /// </summary>
        internal static string ScheduleErrorWaitTimeHelp {
            get {
                return ResourceManager.GetString("ScheduleErrorWaitTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string ScheduleFriHelp {
            get {
                return ResourceManager.GetString("ScheduleFriHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval of the schedule. For example, if the schedule is performed weekly and the interval is 2, then the schedule is done every second week..
        /// </summary>
        internal static string ScheduleIntervalHelp {
            get {
                return ResourceManager.GetString("ScheduleIntervalHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ScheduleItemExecute {
            get {
                object obj = ResourceManager.GetObject("ScheduleItemExecute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScheduleItemOff {
            get {
                object obj = ResourceManager.GetObject("ScheduleItemOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScheduleItemOn {
            get {
                object obj = ResourceManager.GetObject("ScheduleItemOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ScheduleItems {
            get {
                object obj = ResourceManager.GetObject("ScheduleItems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount devices that can be read simultaneously..
        /// </summary>
        internal static string ScheduleMaxThreadCountHelp {
            get {
                return ResourceManager.GetString("ScheduleMaxThreadCountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string ScheduleMonHelp {
            get {
                return ResourceManager.GetString("ScheduleMonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the scheduled task. Name cannot be a number or an empty field..
        /// </summary>
        internal static string ScheduleNameHelp {
            get {
                return ResourceManager.GetString("ScheduleNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection of the repeat mode of the schedule. Schedule can be done once or it can be repeated weekly, daily or monthly. If the repeat mode is weekly, every day of the week is selected as default. Days not needed can be chosen out. If the repeat mode is monthly, the day of the month needs to be given..
        /// </summary>
        internal static string ScheduleRepeatModeHelp {
            get {
                return ResourceManager.GetString("ScheduleRepeatModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string ScheduleSatHelp {
            get {
                return ResourceManager.GetString("ScheduleSatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date when the schedule starts..
        /// </summary>
        internal static string ScheduleStartDateHelp {
            get {
                return ResourceManager.GetString("ScheduleStartDateHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Start Date.
        /// </summary>
        internal static string ScheduleStartTimeTxt {
            get {
                return ResourceManager.GetString("ScheduleStartTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string ScheduleSunHelp {
            get {
                return ResourceManager.GetString("ScheduleSunHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting the target of the scheduled tasks. The target must be set..
        /// </summary>
        internal static string ScheduleTargetHelp {
            get {
                return ResourceManager.GetString("ScheduleTargetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string ScheduleThuHelp {
            get {
                return ResourceManager.GetString("ScheduleThuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of the transactions..
        /// </summary>
        internal static string ScheduleTransactionCountHelp {
            get {
                return ResourceManager.GetString("ScheduleTransactionCountHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time when the transaction ends..
        /// </summary>
        internal static string ScheduleTransactionEndTimeHelp {
            get {
                return ResourceManager.GetString("ScheduleTransactionEndTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time when the transaction starts..
        /// </summary>
        internal static string ScheduleTransactionStartTimeHelp {
            get {
                return ResourceManager.GetString("ScheduleTransactionStartTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string ScheduleTueHelp {
            get {
                return ResourceManager.GetString("ScheduleTueHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Tasks.
        /// </summary>
        internal static string ScheduleTxt {
            get {
                return ResourceManager.GetString("ScheduleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting time between transactions..
        /// </summary>
        internal static string ScheduleUpdateFrequencyHelp {
            get {
                return ResourceManager.GetString("ScheduleUpdateFrequencyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string ScheduleWedHelp {
            get {
                return ResourceManager.GetString("ScheduleWedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one day of week must be set..
        /// </summary>
        internal static string ScheduleWeekdaysNotSetTxt {
            get {
                return ResourceManager.GetString("ScheduleWeekdaysNotSetTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondly.
        /// </summary>
        internal static string SecondTxt {
            get {
                return ResourceManager.GetString("SecondTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAllTxt {
            get {
                return ResourceManager.GetString("SelectAllTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set media settings.
        /// </summary>
        internal static string SetMediaSettingsTxt {
            get {
                return ResourceManager.GetString("SetMediaSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction count or end time must be set..
        /// </summary>
        internal static string SetTransactionCountOrEndTxt {
            get {
                return ResourceManager.GetString("SetTransactionCountOrEndTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notifies.
        /// </summary>
        internal static string ShowNotifiesTxt {
            get {
                return ResourceManager.GetString("ShowNotifiesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Properties.
        /// </summary>
        internal static string TablePropertiesTxt {
            get {
                return ResourceManager.GetString("TablePropertiesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string TablesTxt {
            get {
                return ResourceManager.GetString("TablesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Wizard.
        /// </summary>
        internal static string TableWizardTxt {
            get {
                return ResourceManager.GetString("TableWizardTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target must be set..
        /// </summary>
        internal static string TargetMustBeSetTxt {
            get {
                return ResourceManager.GetString("TargetMustBeSetTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string TargetTxt {
            get {
                return ResourceManager.GetString("TargetTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Count.
        /// </summary>
        internal static string TransactionCountTxt {
            get {
                return ResourceManager.GetString("TransactionCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction end time is before start time..
        /// </summary>
        internal static string TransactionEndBeforeStartTxt {
            get {
                return ResourceManager.GetString("TransactionEndBeforeStartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction End Time.
        /// </summary>
        internal static string TransactionEndTimeTxt {
            get {
                return ResourceManager.GetString("TransactionEndTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Start Time.
        /// </summary>
        internal static string TransactionStartTimeTxt {
            get {
                return ResourceManager.GetString("TransactionStartTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Start Time.
        /// </summary>
        internal static string TransactionStartTimeTxt1 {
            get {
                return ResourceManager.GetString("TransactionStartTimeTxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string TransactionTxt {
            get {
                return ResourceManager.GetString("TransactionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeTxt {
            get {
                return ResourceManager.GetString("TypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UnitTxt {
            get {
                return ResourceManager.GetString("UnitTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap unlike {
            get {
                object obj = ResourceManager.GetObject("unlike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want write changed values to devices?.
        /// </summary>
        internal static string UpdateChangedValuesTxt {
            get {
                return ResourceManager.GetString("UpdateChangedValuesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        internal static string UpdateFrequencyTxt {
            get {
                return ResourceManager.GetString("UpdateFrequencyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Preset Device settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdatePresetDevicesOnlineTxt {
            get {
                return ResourceManager.GetString("UpdatePresetDevicesOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ValueTxt {
            get {
                return ResourceManager.GetString("ValueTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Time:.
        /// </summary>
        internal static string WaitTimeTxt {
            get {
                return ResourceManager.GetString("WaitTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string WeeklyTxt {
            get {
                return ResourceManager.GetString("WeeklyTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard is complete, press Finish to continue..
        /// </summary>
        internal static string WizardFinishTitleTxt {
            get {
                return ResourceManager.GetString("WizardFinishTitleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Finish to continue or Back to alter settings..
        /// </summary>
        internal static string WizardFinishTxt {
            get {
                return ResourceManager.GetString("WizardFinishTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will guide you through general settings of the device.
        /// </summary>
        internal static string WizardStartTxt {
            get {
                return ResourceManager.GetString("WizardStartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string WriteTxt {
            get {
                return ResourceManager.GetString("WriteTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing....
        /// </summary>
        internal static string WritingTxt {
            get {
                return ResourceManager.GetString("WritingTxt", resourceCulture);
            }
        }
    }
}
