//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.DeviceSuite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ApplicationType {
            get {
                return ((int)(this["ApplicationType"]));
            }
            set {
                this["ApplicationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowToolBar {
            get {
                return ((bool)(this["ShowToolBar"]));
            }
            set {
                this["ShowToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowStatusBar {
            get {
                return ((bool)(this["ShowStatusBar"]));
            }
            set {
                this["ShowStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DeviceListColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeviceListColumns"]));
            }
            set {
                this["DeviceListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DeviceTreeWidth {
            get {
                return ((int)(this["DeviceTreeWidth"]));
            }
            set {
                this["DeviceTreeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int PropertyTreeWidth {
            get {
                return ((int)(this["PropertyTreeWidth"]));
            }
            set {
                this["PropertyTreeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int EditorHeight {
            get {
                return ((int)(this["EditorHeight"]));
            }
            set {
                this["EditorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DevicesHeight {
            get {
                return ((int)(this["DevicesHeight"]));
            }
            set {
                this["DevicesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EventColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EventColumns"]));
            }
            set {
                this["EventColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ScheduleColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ScheduleColumns"]));
            }
            set {
                this["ScheduleColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MruFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MruFiles"]));
            }
            set {
                this["MruFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection PropertyColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PropertyColumns"]));
            }
            set {
                this["PropertyColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EditorSelectedMedia {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EditorSelectedMedia"]));
            }
            set {
                this["EditorSelectedMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection EditorSelectedMediaSettings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EditorSelectedMediaSettings"]));
            }
            set {
                this["EditorSelectedMediaSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TraceLevel {
            get {
                return ((int)(this["TraceLevel"]));
            }
            set {
                this["TraceLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gurux.org/GuruxDevicePublisher")]
        public string UpdateServer {
            get {
                return ((string)(this["UpdateServer"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DisabledProtocols {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DisabledProtocols"]));
            }
            set {
                this["DisabledProtocols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bounds {
            get {
                return ((string)(this["Bounds"]));
            }
            set {
                this["Bounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TraceFollowLast {
            get {
                return ((bool)(this["TraceFollowLast"]));
            }
            set {
                this["TraceFollowLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EventFollowLast {
            get {
                return ((bool)(this["EventFollowLast"]));
            }
            set {
                this["EventFollowLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWizardStartPage {
            get {
                return ((bool)(this["ShowWizardStartPage"]));
            }
            set {
                this["ShowWizardStartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int TraceViewWidth {
            get {
                return ((int)(this["TraceViewWidth"]));
            }
            set {
                this["TraceViewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TaskViewColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TaskViewColumns"]));
            }
            set {
                this["TaskViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TraceViewColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TraceViewColumns"]));
            }
            set {
                this["TraceViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DirectorTraceViewColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DirectorTraceViewColumns"]));
            }
            set {
                this["DirectorTraceViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Usermode {
            get {
                return ((int)(this["Usermode"]));
            }
            set {
                this["Usermode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DCTreeWidth {
            get {
                return ((int)(this["DCTreeWidth"]));
            }
            set {
                this["DCTreeWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DirectorHeight {
            get {
                return ((int)(this["DirectorHeight"]));
            }
            set {
                this["DirectorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DCDevicesHeight {
            get {
                return ((int)(this["DCDevicesHeight"]));
            }
            set {
                this["DCDevicesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DCDeviceListColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DCDeviceListColumns"]));
            }
            set {
                this["DCDeviceListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DCEventColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DCEventColumns"]));
            }
            set {
                this["DCEventColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DCPropertyColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DCPropertyColumns"]));
            }
            set {
                this["DCPropertyColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DCScheduleColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DCScheduleColumns"]));
            }
            set {
                this["DCScheduleColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DCTraceViewColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DCTraceViewColumns"]));
            }
            set {
                this["DCTraceViewColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmiDBUserName {
            get {
                return ((string)(this["AmiDBUserName"]));
            }
            set {
                this["AmiDBUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmiDBPassword {
            get {
                return ((string)(this["AmiDBPassword"]));
            }
            set {
                this["AmiDBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string AmiHostName {
            get {
                return ((string)(this["AmiHostName"]));
            }
            set {
                this["AmiHostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmiDatabaseHostName {
            get {
                return ((string)(this["AmiDatabaseHostName"]));
            }
            set {
                this["AmiDatabaseHostName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("guruxami")]
        public string AmiDatabaseName {
            get {
                return ((string)(this["AmiDatabaseName"]));
            }
            set {
                this["AmiDatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gurux")]
        public string AmiUserName {
            get {
                return ((string)(this["AmiUserName"]));
            }
            set {
                this["AmiUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gurux")]
        public string AmiPassword {
            get {
                return ((string)(this["AmiPassword"]));
            }
            set {
                this["AmiPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")]
        public global::System.Guid AmiDCGuid {
            get {
                return ((global::System.Guid)(this["AmiDCGuid"]));
            }
            set {
                this["AmiDCGuid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AmiDatabaseTablePrefix {
            get {
                return ((string)(this["AmiDatabaseTablePrefix"]));
            }
            set {
                this["AmiDatabaseTablePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ErrorMaximumCount {
            get {
                return ((int)(this["ErrorMaximumCount"]));
            }
            set {
                this["ErrorMaximumCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TraceMaximumCount {
            get {
                return ((int)(this["TraceMaximumCount"]));
            }
            set {
                this["TraceMaximumCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AmiDataCollectors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AmiDataCollectors"]));
            }
            set {
                this["AmiDataCollectors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AmiEnabled {
            get {
                return ((bool)(this["AmiEnabled"]));
            }
            set {
                this["AmiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DataCollectorListColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DataCollectorListColumns"]));
            }
            set {
                this["DataCollectorListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DeviceProfilesListColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DeviceProfilesListColumns"]));
            }
            set {
                this["DeviceProfilesListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection TaskListColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TaskListColumns"]));
            }
            set {
                this["TaskListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection UnAssignedListColumns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UnAssignedListColumns"]));
            }
            set {
                this["UnAssignedListColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeviceTreeShowDevices {
            get {
                return ((bool)(this["DeviceTreeShowDevices"]));
            }
            set {
                this["DeviceTreeShowDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeviceTreeShowCategories {
            get {
                return ((bool)(this["DeviceTreeShowCategories"]));
            }
            set {
                this["DeviceTreeShowCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeviceTreeShowTables {
            get {
                return ((bool)(this["DeviceTreeShowTables"]));
            }
            set {
                this["DeviceTreeShowTables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeviceTreeShowProperties {
            get {
                return ((bool)(this["DeviceTreeShowProperties"]));
            }
            set {
                this["DeviceTreeShowProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeviceTreeShowPropertyValue {
            get {
                return ((bool)(this["DeviceTreeShowPropertyValue"]));
            }
            set {
                this["DeviceTreeShowPropertyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CommandPrompSettings {
            get {
                return ((string)(this["CommandPrompSettings"]));
            }
            set {
                this["CommandPrompSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowMediaTrace {
            get {
                return ((bool)(this["ShowMediaTrace"]));
            }
            set {
                this["ShowMediaTrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GetDataCollectorsAutomatically {
            get {
                return ((bool)(this["GetDataCollectorsAutomatically"]));
            }
            set {
                this["GetDataCollectorsAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GetDevicesAutomatically {
            get {
                return ((bool)(this["GetDevicesAutomatically"]));
            }
            set {
                this["GetDevicesAutomatically"] = value;
            }
        }
    }
}
